## Some comparisons of filtering and smoothing (can be with or without the viewer)

### Hint for your task 2)
#### You must implement your filtering / smoothing in the HMMFilter / HMMSmoother classes in the file Filters. For the filter, this means also that you can use the visualisation through the Localizer, but you can call filter / smooth also directly from here, without the Localiser. Note also, that you must make use of the given models and the robot simulator in RobotSim!


In [1]:
# In this cell, you can write your own "main" to run and evaluate your 
# implementation without using the visualisation (should be considerably faster!)

from models import *
from Filters import HMMFilter, HMMSmoother

import numpy as np
import matplotlib.pyplot as plt
import random

num_states = 5  # Change this according to your problem setup

# Transition Model (State Transition Probabilities)
tm = np.array([
    [0.6, 0.2, 0.1, 0.05, 0.05],
    [0.1, 0.6, 0.2, 0.05, 0.05],
    [0.05, 0.1, 0.6, 0.2, 0.05],
    [0.05, 0.05, 0.2, 0.6, 0.1],
    [0.1, 0.05, 0.05, 0.2, 0.6]
])

# Observation Model (Emission Probabilities)
om = np.array([
    [0.7, 0.2, 0.05, 0.03, 0.02],
    [0.2, 0.6, 0.1, 0.07, 0.03],
    [0.05, 0.1, 0.7, 0.1, 0.05],
    [0.03, 0.07, 0.1, 0.6, 0.2],
    [0.02, 0.03, 0.05, 0.2, 0.7]
])

# Sensor Model (Likelihoods of sensor readings)
sm = np.array([0.8, 0.1, 0.05, 0.03, 0.02])

# Initial state distribution (Assuming uniform)
initial_probs = np.ones(num_states) / num_states

# Create filter and smoother instances
hmm_filter = HMMFilter(initial_probs, tm, om, sm)
hmm_smoother = HMMSmoother(tm, om, sm)

# Define a sequence of sensor readings (simulated)
sensor_readings = [0, 1, 2, 1, 0]  # Example sensor readings

# Run filtering
filtered_probs = []
for sensor in sensor_readings:
    filtered_prob = hmm_filter.filter(sensor)
    filtered_probs.append(filtered_prob)

# Run smoothing
smoothed_probs = hmm_smoother.smooth(sensor_readings, filtered_probs[-1])

# Print results
print("\nFiltered Probabilities:")
for i, prob in enumerate(filtered_probs):
    print(f"Time step {i}: {prob}")

print("\nSmoothed Probabilities:")
print(smoothed_probs)
# ...  


Filtered Probabilities:
Time step 0: [0.672      0.21333333 0.06133333 0.0352     0.01813333]
Time step 1: [0.31708864 0.59832856 0.056852   0.02092091 0.00680989]
Time step 2: [0.06413405 0.21632909 0.66994759 0.03579025 0.01379902]
Time step 3: [0.09377769 0.61655542 0.22262033 0.05841603 0.00863053]
Time step 4: [0.47826559 0.42618699 0.07159017 0.01802508 0.00593217]

Smoothed Probabilities:
[[0.23454129 0.43784134 0.16495743 0.09431415 0.06834578]
 [0.17588163 0.2646052  0.33605772 0.14800525 0.07545019]
 [0.36395809 0.3762929  0.1048492  0.07143279 0.08346702]
 [0.49866667 0.216      0.09813333 0.08       0.1072    ]
 [0.2        0.2        0.2        0.2        0.2       ]]
